---

  - name: Create DNS record for www project
    cloudflare_dns:
      zone: "{{ dns_zone }}"
      record: "{{ dns_www_record }}"
      type: A
      value: "{{ working_host }}"
      account_email: "{{ dns_cloudflare_account_email }}"
      account_api_token: "{{ dns_cloudflare_api_token }}"
