---

  - name: Create DNS record for www project
    cloudflare_dns:
      zone: "{{ dns_zone }}"
      record: "{{ dns_www_record }}"
      type: A
      proxied: yes
      value: "{{ working_host }}"
      account_email: "{{ dns_cloudflare_account_email }}"
      account_api_token: "{{ dns_cloudflare_api_token }}"
      state: present

  - name: Remove DNS record for ssh
    cloudflare_dns:
      zone: "{{ dns_zone }}"
      record: "ssh"
      type: A
      proxied: no
      value: "{{ working_host }}"
      account_email: "{{ dns_cloudflare_account_email }}"
      account_api_token: "{{ dns_cloudflare_api_token }}"
      state: absent

  - name: Create DNS record for blog
    cloudflare_dns:
      zone: "{{ dns_zone }}"
      record: "{{ dns_blog_record }}"
      type: A
      proxied: yes
      value: "{{ working_host }}"
      account_email: "{{ dns_cloudflare_account_email }}"
      account_api_token: "{{ dns_cloudflare_api_token }}"
      state: present
