---

# These instructions were inspired from,
# ref: https://certbot.eff.org/lets-encrypt/ubuntubionic-nginx
#
# NOTE: From an earlier step, we already have the universe repository activated.

  - name: Register certbot PPA repository
    apt_repository:
      repo: 'ppa:certbot/certbot'

  - name: Install certbot and related tools
    apt:
      name: "{{ item }}"
      state: present
      update_cache: yes
    with_items:
      - software-properties-common
      - certbot
      - python3-certbot-nginx
      - python3-certbot-dns-cloudflare

# We need to create a CloudFlare configuration file;
# ref: https://certbot-dns-cloudflare.readthedocs.io/en/stable/
# ref: https://mangolassi.it/topic/18355/setup-letsencrypt-certbot-with-cloudflare-dns-authentication-ubuntu

  - name: Create .secrets folder
    file:
      path: /root/.secrets
      state: directory
      mode: '0700'

  - name: Copy over configuration file
    template: 
      src: cloudflare.cfg.j2 
      dest: /root/.secrets/cloudflare.cfg
      mode: '0400'

  - name: Request certificates from Lets Encrypt 
    shell: > 
      certbot certonly --dns-cloudflare 
      --dns-cloudflare-credentials /root/.secrets/cloudflare.cfg 
      -d {{ dns_zone }},*.{{ dns_zone }} 
      --preferred-challenges dns-01 
      -m {{ dns_cloudflare_account_email }} 
      -n 
      --agree-tos

# NOTE: The above command will also install a systemd timer which automatically
#       runs to renew the certificates, if needed. I *think* it runs every 6 or 
#       8 hours. You can see the full list of timers active on the system with 
#       the following command, 
#       $ systemctl list-timers

# NOTE 2: The -n in the above command means "run non-interactively" and the
#         --agree-tos means that we are agreeing to their terms and conditions.

  - name: Generate DH parameters with the default size (4096 bits)
    shell: openssl dhparam -dsaparam -out /etc/letsencrypt/ssl-dhparams.pem 4096

  # openssl_dhparam:
    #   path: /etc/letsencrypt/ssl-dhparams.pem
