---

  - name: Install nginx
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - nginx

  - name: Allow HTTP for nginx in firewall
    ufw:
      rule: allow
      name: "Nginx HTTP"

  - name: Allow HTTPS for nginx in firewall
    ufw:
      rule: allow
      name: "Nginx Full"

  - name: Allow SSH in firewall
    ufw:
      rule: allow
      name: "OpenSSH"

  - name: Activate firewall
    ufw:
      state: enabled

  - name: install nginx configuration file for default (HTTP redirect)
    template: 
      src: default_nginx.j2 
      dest: /etc/nginx/sites-available/default_nginx
    notify:
      - Restart nginx

  - name: Activate default_nginx on nginx via symbolic link
    file:
      state: link
      src: /etc/nginx/sites-available/default_nginx
      dest: /etc/nginx/sites-enabled/default_nginx
    notify:
      - Restart nginx      
