---

  - name: Create symlink to webapp source folder
    file:
      state: link
      src: /home/{{ webapp_user }}/web_project/blog
      dest: /var/www/site-blog

  - name: Publish dotNet project
    become: yes
    become_user: "{{ webapp_user }}"
    shell: dotnet publish
    args:
      chdir: /var/www/site-blog
    notify:
      - Restart dotNetBlogApp
      - Restart nginx

  - name: install dotNetBlogApp systemd unit file
    template: 
      src: blogapp.service.j2 
      dest: /etc/systemd/system/blogapp.service
    notify:
      - Restart dotNetBlogApp

  - name: install nginx configuration file for dotnet_blogapp
    template: 
      src: dotnet_blogapp.j2 
      dest: /etc/nginx/sites-available/dotnet_blogapp
    notify:
      - Restart nginx

  - name: Activate dotnet_blogapp on nginx via symbolic link
    file:
      state: link
      src: /etc/nginx/sites-available/dotnet_blogapp
      dest: /etc/nginx/sites-enabled/dotnet_blogapp
    notify:
      - Restart nginx      
