---

  - name: record environment variables for Terraria server
    template: 
      src: terraria-server-env-vars.sh.j2
      dest: /etc/profile.d/terraria-server-env-vars.sh

  - name: Clone terraria_on_digital_ocean repo
    become: yes
    become_user: "{{ webapp_user }}"
    git:
      repo: "{{ terraria_setup_server_repo }}"
      dest: /home/{{ webapp_user }}/terraria_on_digital_ocean
      version: master
      force: yes

  - name: Installing dependencies for ansible
    apt:
      name: "{{ item }}"
      state: present
      update_cache: yes
    with_items:
      - 'apt-transport-https'
      - 'ca-certificates'
      - 'curl'
      - 'gnupg-agent'
      - 'software-properties-common'

  - name: Add ansible repository on remote droplet
    apt_repository:
      repo: ppa:ansible/ansible

  - name: Installing ansible
    apt:
      name: "{{ item }}"
      state: present
      update_cache: yes
    with_items:
      - 'ansible'

  - name: Add .ssh directory for webapp_user
    file:
      path: /home/{{ webapp_user }}/.ssh
      state: directory
      mode: 0700
      owner: "{{ webapp_user }}"
      group: "{{ webapp_user }}"

  - name: Copy over SSH keys
    copy:
      src: /root/.ssh/id_rsa_e9f326a7c682d116c4fad602253958b4
      dest: /home/{{ webapp_user }}/.ssh/id_rsa
      owner: "{{ webapp_user }}"
      group: "{{ webapp_user }}"
      mode: 0600

